"use strict";

(function initializeTriageData(global) {
  const patients = [
    {
      id: "P-001",
      name: "김하준",
      age: 3,
      sex: "남",
      symptom: "수영장 사고 후 청색증과 반응 저하",
      consciousness: "무반응",
      temperature: 37.0,
      pulse: 118,
      respiration: 28,
      systolicBP: 84,
      diastolicBP: 52,
      spo2: 88,
      pain: 0,
      answerGrade: 1,
    },
    {
      id: "P-002",
      name: "이서윤",
      age: 6,
      sex: "여",
      symptom: "고열 뒤 횡설수설하며 숨이 참",
      consciousness: "혼란",
      temperature: 37.7,
      pulse: 105,
      respiration: 25,
      systolicBP: 95,
      diastolicBP: 61,
      spo2: 93,
      pain: 3,
      answerGrade: 2,
    },
    {
      id: "P-003",
      name: "박도윤",
      age: 9,
      sex: "남",
      symptom: "인후통과 지속되는 고열",
      consciousness: "명료",
      temperature: 39.2,
      pulse: 104,
      respiration: 22,
      systolicBP: 106,
      diastolicBP: 67,
      spo2: 95,
      pain: 4,
      answerGrade: 3,
    },
    {
      id: "P-004",
      name: "최지우",
      age: 12,
      sex: "여",
      symptom: "달리다 발목을 접질림",
      consciousness: "명료",
      temperature: 36.7,
      pulse: 88,
      respiration: 18,
      systolicBP: 108,
      diastolicBP: 68,
      spo2: 99,
      pain: 5,
      answerGrade: 4,
    },
    {
      id: "P-005",
      name: "정민준",
      age: 15,
      sex: "남",
      symptom: "손가락의 얕은 찰과상",
      consciousness: "명료",
      temperature: 36.6,
      pulse: 72,
      respiration: 14,
      systolicBP: 112,
      diastolicBP: 70,
      spo2: 99,
      pain: 2,
      answerGrade: 5,
    },
    {
      id: "P-006",
      name: "윤서현",
      age: 18,
      sex: "여",
      symptom: "갑작스러운 두근거림과 어지럼증",
      consciousness: "명료",
      temperature: 36.9,
      pulse: 155,
      respiration: 18,
      systolicBP: 102,
      diastolicBP: 64,
      spo2: 98,
      pain: 2,
      answerGrade: 1,
    },
    {
      id: "P-007",
      name: "강지민",
      age: 21,
      sex: "남",
      symptom: "가슴 두근거림과 식은땀",
      consciousness: "명료",
      temperature: 37.1,
      pulse: 126,
      respiration: 15,
      systolicBP: 104,
      diastolicBP: 66,
      spo2: 97,
      pain: 3,
      answerGrade: 2,
    },
    {
      id: "P-008",
      name: "조수빈",
      age: 24,
      sex: "여",
      symptom: "기침과 숨을 쉴 때의 흉통",
      consciousness: "명료",
      temperature: 37.6,
      pulse: 76,
      respiration: 22,
      systolicBP: 116,
      diastolicBP: 72,
      spo2: 97,
      pain: 5,
      answerGrade: 2,
    },
    {
      id: "P-009",
      name: "한예린",
      age: 27,
      sex: "여",
      symptom: "주방 칼에 베인 손바닥 상처",
      consciousness: "명료",
      temperature: 36.8,
      pulse: 76,
      respiration: 18,
      systolicBP: 118,
      diastolicBP: 74,
      spo2: 99,
      pain: 5,
      answerGrade: 4,
    },
    {
      id: "P-010",
      name: "임준호",
      age: 30,
      sex: "남",
      symptom: "가벼운 소화불량과 속쓰림",
      consciousness: "명료",
      temperature: 36.5,
      pulse: 68,
      respiration: 14,
      systolicBP: 120,
      diastolicBP: 78,
      spo2: 99,
      pain: 2,
      answerGrade: 5,
    },
    {
      id: "P-011",
      name: "신유진",
      age: 33,
      sex: "여",
      symptom: "심한 호흡곤란과 입술 청색증",
      consciousness: "명료",
      temperature: 37.2,
      pulse: 74,
      respiration: 34,
      systolicBP: 110,
      diastolicBP: 70,
      spo2: 91,
      pain: 4,
      answerGrade: 1,
    },
    {
      id: "P-012",
      name: "오현우",
      age: 36,
      sex: "남",
      symptom: "기립 시 어지럼증과 식은땀",
      consciousness: "명료",
      temperature: 36.4,
      pulse: 75,
      respiration: 14,
      systolicBP: 88,
      diastolicBP: 58,
      spo2: 98,
      pain: 1,
      answerGrade: 2,
    },
    {
      id: "P-013",
      name: "서미진",
      age: 39,
      sex: "여",
      symptom: "오한을 동반한 복통과 발열",
      consciousness: "명료",
      temperature: 38.5,
      pulse: 74,
      respiration: 14,
      systolicBP: 114,
      diastolicBP: 72,
      spo2: 98,
      pain: 6,
      answerGrade: 3,
    },
    {
      id: "P-014",
      name: "권동현",
      age: 42,
      sex: "남",
      symptom: "무거운 물건을 든 뒤 허리 통증",
      consciousness: "명료",
      temperature: 36.6,
      pulse: 92,
      respiration: 14,
      systolicBP: 126,
      diastolicBP: 81,
      spo2: 98,
      pain: 6,
      answerGrade: 4,
    },
    {
      id: "P-015",
      name: "황지영",
      age: 45,
      sex: "여",
      symptom: "오래된 손목 통증의 재발",
      consciousness: "명료",
      temperature: 36.7,
      pulse: 74,
      respiration: 13,
      systolicBP: 124,
      diastolicBP: 79,
      spo2: 99,
      pain: 3,
      answerGrade: 5,
    },
    {
      id: "P-016",
      name: "송성호",
      age: 48,
      sex: "남",
      symptom: "검은 변 뒤 심한 현기증과 창백함",
      consciousness: "명료",
      temperature: 36.3,
      pulse: 78,
      respiration: 15,
      systolicBP: 72,
      diastolicBP: 45,
      spo2: 97,
      pain: 4,
      answerGrade: 1,
    },
    {
      id: "P-017",
      name: "전은정",
      age: 51,
      sex: "여",
      symptom: "천명음과 점점 심해지는 숨참",
      consciousness: "명료",
      temperature: 36.9,
      pulse: 76,
      respiration: 15,
      systolicBP: 118,
      diastolicBP: 75,
      spo2: 92,
      pain: 2,
      answerGrade: 2,
    },
    {
      id: "P-018",
      name: "홍재훈",
      age: 54,
      sex: "남",
      symptom: "운동 후 지속되는 가슴 압박감",
      consciousness: "명료",
      temperature: 36.8,
      pulse: 101,
      respiration: 15,
      systolicBP: 132,
      diastolicBP: 84,
      spo2: 98,
      pain: 6,
      answerGrade: 3,
    },
    {
      id: "P-019",
      name: "고미숙",
      age: 57,
      sex: "여",
      symptom: "계단에서 넘어진 뒤 무릎 통증",
      consciousness: "명료",
      temperature: 36.5,
      pulse: 78,
      respiration: 17,
      systolicBP: 128,
      diastolicBP: 80,
      spo2: 98,
      pain: 6,
      answerGrade: 3,
    },
    {
      id: "P-020",
      name: "문영호",
      age: 60,
      sex: "남",
      symptom: "며칠째 이어지는 가벼운 변비",
      consciousness: "명료",
      temperature: 36.6,
      pulse: 66,
      respiration: 12,
      systolicBP: 130,
      diastolicBP: 82,
      spo2: 98,
      pain: 2,
      answerGrade: 5,
    },
    {
      id: "P-021",
      name: "양정숙",
      age: 63,
      sex: "여",
      symptom: "갑작스러운 숨참과 손끝 청색증",
      consciousness: "명료",
      temperature: 36.7,
      pulse: 76,
      respiration: 15,
      systolicBP: 122,
      diastolicBP: 76,
      spo2: 86,
      pain: 3,
      answerGrade: 1,
    },
    {
      id: "P-022",
      name: "손병철",
      age: 66,
      sex: "남",
      symptom: "말이 느려지고 잠에서 잘 깨지 않음",
      consciousness: "혼미",
      temperature: 36.6,
      pulse: 72,
      respiration: 14,
      systolicBP: 124,
      diastolicBP: 78,
      spo2: 97,
      pain: 1,
      answerGrade: 3,
    },
    {
      id: "P-023",
      name: "배순자",
      age: 69,
      sex: "여",
      symptom: "기침과 가벼운 호흡곤란",
      consciousness: "명료",
      temperature: 37.4,
      pulse: 74,
      respiration: 14,
      systolicBP: 126,
      diastolicBP: 80,
      spo2: 95,
      pain: 2,
      answerGrade: 3,
    },
    {
      id: "P-024",
      name: "백영수",
      age: 72,
      sex: "남",
      symptom: "넘어진 뒤 팔꿈치 부종",
      consciousness: "명료",
      temperature: 36.4,
      pulse: 83,
      respiration: 14,
      systolicBP: 134,
      diastolicBP: 82,
      spo2: 98,
      pain: 5,
      answerGrade: 4,
    },
    {
      id: "P-025",
      name: "허정희",
      age: 75,
      sex: "여",
      symptom: "가벼운 콧물과 목 불편감",
      consciousness: "명료",
      temperature: 36.5,
      pulse: 70,
      respiration: 15,
      systolicBP: 132,
      diastolicBP: 78,
      spo2: 98,
      pain: 1,
      answerGrade: 5,
    },
    {
      id: "P-026",
      name: "남기석",
      age: 78,
      sex: "남",
      symptom: "의식과 호흡이 없고 맥박이 만져지지 않음",
      consciousness: "무반응",
      temperature: 35.8,
      pulse: 0,
      respiration: 0,
      systolicBP: 0,
      diastolicBP: 0,
      spo2: 0,
      pain: 0,
      answerGrade: 1,
    },
    {
      id: "P-027",
      name: "심복순",
      age: 81,
      sex: "여",
      symptom: "가래와 빠른 호흡을 동반한 폐렴 의심",
      consciousness: "명료",
      temperature: 37.6,
      pulse: 76,
      respiration: 27,
      systolicBP: 104,
      diastolicBP: 65,
      spo2: 97,
      pain: 3,
      answerGrade: 2,
    },
    {
      id: "P-028",
      name: "노춘자",
      age: 84,
      sex: "여",
      symptom: "감기 뒤 남은 숨참과 피로",
      consciousness: "명료",
      temperature: 36.8,
      pulse: 75,
      respiration: 14,
      systolicBP: 128,
      diastolicBP: 76,
      spo2: 94.5,
      pain: 2,
      answerGrade: 3,
    },
    {
      id: "P-029",
      name: "주만식",
      age: 87,
      sex: "남",
      symptom: "밤새 이어진 가벼운 어깨 통증",
      consciousness: "명료",
      temperature: 36.4,
      pulse: 78,
      respiration: 19,
      systolicBP: 136,
      diastolicBP: 82,
      spo2: 97,
      pain: 4,
      answerGrade: 4,
    },
    {
      id: "P-030",
      name: "구옥분",
      age: 90,
      sex: "여",
      symptom: "보청기 점검 중 발견한 가벼운 귀 불편감",
      consciousness: "명료",
      temperature: 36.3,
      pulse: 64,
      respiration: 12,
      systolicBP: 138,
      diastolicBP: 80,
      spo2: 97,
      pain: 1,
      answerGrade: 5,
    },
  ];

  const frozenPatients = Object.freeze(
    patients.map(function freezePatient(patient) {
      return Object.freeze(patient);
    }),
  );

  global.TriageData = Object.freeze({ patients: frozenPatients });
})(globalThis);
